// psyduck.proto is the wire contract between a psyduck host and a plugin
// subprocess, spoken over hashicorp/go-plugin's gRPC transport. It mirrors
// the sdk surface one-to-one:
//
//   sdk.Plugin.Name/Resources  <->  Driver.Schema
//   sdk.Plugin.Bind            <->  Driver.Bind   (returns an instance handle)
//   sdk.Instance.Produce       <->  Driver.Produce   (server stream)
//   sdk.Instance.Consume       <->  Driver.Consume   (bidirectional stream)
//   sdk.Instance.Transform     <->  Driver.Transform (unary)
//   sdk.Instance.Close         <->  Driver.Close
//
// Data items are opaque bytes, exactly as they are on the sdk's channel
// surface. Config crosses as the JSON object ConfigBlock.Encode produces.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: psyduck.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_psyduck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{0}
}

// Spec mirrors sdk.Spec. type holds the sdk.SpecType enum value; the
// default value crosses JSON-encoded (empty = no default).
type Spec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Type          uint32                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	ElemType      *Spec                  `protobuf:"bytes,5,opt,name=elem_type,json=elemType,proto3" json:"elem_type,omitempty"`
	Fields        []*Spec                `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	DefaultJson   []byte                 `protobuf:"bytes,7,opt,name=default_json,json=defaultJson,proto3" json:"default_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_psyduck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Spec) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Spec) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Spec) GetElemType() *Spec {
	if x != nil {
		return x.ElemType
	}
	return nil
}

func (x *Spec) GetFields() []*Spec {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Spec) GetDefaultJson() []byte {
	if x != nil {
		return x.DefaultJson
	}
	return nil
}

// ResourceDescriptor mirrors sdk.ResourceDescriptor; kinds is the sdk.Kind
// bitmask.
type ResourceDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kinds         uint64                 `protobuf:"varint,2,opt,name=kinds,proto3" json:"kinds,omitempty"`
	Spec          []*Spec                `protobuf:"bytes,3,rep,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDescriptor) Reset() {
	*x = ResourceDescriptor{}
	mi := &file_psyduck_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor) ProtoMessage() {}

func (x *ResourceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceDescriptor) GetKinds() uint64 {
	if x != nil {
		return x.Kinds
	}
	return 0
}

func (x *ResourceDescriptor) GetSpec() []*Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type SchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Resources     []*ResourceDescriptor  `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaResponse) Reset() {
	*x = SchemaResponse{}
	mi := &file_psyduck_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaResponse) ProtoMessage() {}

func (x *SchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaResponse.ProtoReflect.Descriptor instead.
func (*SchemaResponse) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{3}
}

func (x *SchemaResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaResponse) GetResources() []*ResourceDescriptor {
	if x != nil {
		return x.Resources
	}
	return nil
}

// SourceRange mirrors sdk.SourceRange so plugin-side diagnostics can point
// at the config block that configured the instance.
type SourceRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	StartLine     int64                  `protobuf:"varint,2,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	StartCol      int64                  `protobuf:"varint,3,opt,name=start_col,json=startCol,proto3" json:"start_col,omitempty"`
	EndLine       int64                  `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndCol        int64                  `protobuf:"varint,5,opt,name=end_col,json=endCol,proto3" json:"end_col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRange) Reset() {
	*x = SourceRange{}
	mi := &file_psyduck_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRange) ProtoMessage() {}

func (x *SourceRange) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRange.ProtoReflect.Descriptor instead.
func (*SourceRange) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{4}
}

func (x *SourceRange) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *SourceRange) GetStartLine() int64 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *SourceRange) GetStartCol() int64 {
	if x != nil {
		return x.StartCol
	}
	return 0
}

func (x *SourceRange) GetEndLine() int64 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *SourceRange) GetEndCol() int64 {
	if x != nil {
		return x.EndCol
	}
	return 0
}

type BindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          uint64                 `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"` // single sdk.Kind bit
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Config        []byte                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"` // JSON object from ConfigBlock.Encode
	Origin        *SourceRange           `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_psyduck_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{5}
}

func (x *BindRequest) GetKind() uint64 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *BindRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *BindRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *BindRequest) GetOrigin() *SourceRange {
	if x != nil {
		return x.Origin
	}
	return nil
}

// BindResponse carries the plugin-side handle all instance RPCs refer to.
// Bind failures surface as gRPC status errors.
type BindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint64                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindResponse) Reset() {
	*x = BindResponse{}
	mi := &file_psyduck_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResponse) ProtoMessage() {}

func (x *BindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResponse.ProtoReflect.Descriptor instead.
func (*BindResponse) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{6}
}

func (x *BindResponse) GetInstance() uint64 {
	if x != nil {
		return x.Instance
	}
	return 0
}

type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint64                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_psyduck_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{7}
}

func (x *ProduceRequest) GetInstance() uint64 {
	if x != nil {
		return x.Instance
	}
	return 0
}

// Event is one occurrence on a producer's or consumer's output: a data
// item (produce only), an error report, or a consumer's done signal.
// Errors are events, not stream failures — a resource can report errors
// and keep running, exactly like sending on the sdk's errs channel.
//
// done exists because the sdk contract distinguishes a consumer that
// signaled done (normal completion) from one that returned without doing
// so (aborted); a bare stream end cannot carry that distinction.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_Data
	//	*Event_Error
	//	*Event_Done
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_psyduck_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetData() []byte {
	if x != nil {
		if x, ok := x.Event.(*Event_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Event) GetError() string {
	if x != nil {
		if x, ok := x.Event.(*Event_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *Event) GetDone() bool {
	if x != nil {
		if x, ok := x.Event.(*Event_Done); ok {
			return x.Done
		}
	}
	return false
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_Data struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type Event_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Event_Done struct {
	Done bool `protobuf:"varint,3,opt,name=done,proto3,oneof"`
}

func (*Event_Data) isEvent_Event() {}

func (*Event_Error) isEvent_Event() {}

func (*Event_Done) isEvent_Event() {}

// ConsumeChunk is one host->plugin message on a consume stream. The first
// chunk must carry the instance handle; every following chunk carries one
// data item.
type ConsumeChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chunk:
	//
	//	*ConsumeChunk_Instance
	//	*ConsumeChunk_Data
	Chunk         isConsumeChunk_Chunk `protobuf_oneof:"chunk"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeChunk) Reset() {
	*x = ConsumeChunk{}
	mi := &file_psyduck_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeChunk) ProtoMessage() {}

func (x *ConsumeChunk) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeChunk.ProtoReflect.Descriptor instead.
func (*ConsumeChunk) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{9}
}

func (x *ConsumeChunk) GetChunk() isConsumeChunk_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ConsumeChunk) GetInstance() uint64 {
	if x != nil {
		if x, ok := x.Chunk.(*ConsumeChunk_Instance); ok {
			return x.Instance
		}
	}
	return 0
}

func (x *ConsumeChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Chunk.(*ConsumeChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isConsumeChunk_Chunk interface {
	isConsumeChunk_Chunk()
}

type ConsumeChunk_Instance struct {
	Instance uint64 `protobuf:"varint,1,opt,name=instance,proto3,oneof"`
}

type ConsumeChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ConsumeChunk_Instance) isConsumeChunk_Chunk() {}

func (*ConsumeChunk_Data) isConsumeChunk_Chunk() {}

type TransformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint64                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_psyduck_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{10}
}

func (x *TransformRequest) GetInstance() uint64 {
	if x != nil {
		return x.Instance
	}
	return 0
}

func (x *TransformRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// TransformResponse relays the transformer's (out, err) pair. drop marks
// the (nil, nil) case — "silently drop this message" — which proto bytes
// cannot otherwise distinguish from an empty output.
type TransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Drop          bool                   `protobuf:"varint,2,opt,name=drop,proto3" json:"drop,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformResponse) Reset() {
	*x = TransformResponse{}
	mi := &file_psyduck_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformResponse) ProtoMessage() {}

func (x *TransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformResponse.ProtoReflect.Descriptor instead.
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{11}
}

func (x *TransformResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TransformResponse) GetDrop() bool {
	if x != nil {
		return x.Drop
	}
	return false
}

func (x *TransformResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint64                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_psyduck_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_psyduck_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_psyduck_proto_rawDescGZIP(), []int{12}
}

func (x *CloseRequest) GetInstance() uint64 {
	if x != nil {
		return x.Instance
	}
	return 0
}

var File_psyduck_proto protoreflect.FileDescriptor

const file_psyduck_proto_rawDesc = "" +
	"\n" +
	"\rpsyduck.proto\x12\n" +
	"psyduck.v1\"\a\n" +
	"\x05Empty\"\xe8\x01\n" +
	"\x04Spec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x12\n" +
	"\x04type\x18\x04 \x01(\rR\x04type\x12-\n" +
	"\telem_type\x18\x05 \x01(\v2\x10.psyduck.v1.SpecR\belemType\x12(\n" +
	"\x06fields\x18\x06 \x03(\v2\x10.psyduck.v1.SpecR\x06fields\x12!\n" +
	"\fdefault_json\x18\a \x01(\fR\vdefaultJson\"d\n" +
	"\x12ResourceDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05kinds\x18\x02 \x01(\x04R\x05kinds\x12$\n" +
	"\x04spec\x18\x03 \x03(\v2\x10.psyduck.v1.SpecR\x04spec\"b\n" +
	"\x0eSchemaResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\tresources\x18\x02 \x03(\v2\x1e.psyduck.v1.ResourceDescriptorR\tresources\"\x9e\x01\n" +
	"\vSourceRange\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x1d\n" +
	"\n" +
	"start_line\x18\x02 \x01(\x03R\tstartLine\x12\x1b\n" +
	"\tstart_col\x18\x03 \x01(\x03R\bstartCol\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\x03R\aendLine\x12\x17\n" +
	"\aend_col\x18\x05 \x01(\x03R\x06endCol\"\x86\x01\n" +
	"\vBindRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\x04R\x04kind\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06config\x18\x03 \x01(\fR\x06config\x12/\n" +
	"\x06origin\x18\x04 \x01(\v2\x17.psyduck.v1.SourceRangeR\x06origin\"*\n" +
	"\fBindResponse\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\x04R\binstance\",\n" +
	"\x0eProduceRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\x04R\binstance\"T\n" +
	"\x05Event\x12\x14\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x12\x14\n" +
	"\x04done\x18\x03 \x01(\bH\x00R\x04doneB\a\n" +
	"\x05event\"K\n" +
	"\fConsumeChunk\x12\x1c\n" +
	"\binstance\x18\x01 \x01(\x04H\x00R\binstance\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\a\n" +
	"\x05chunk\"B\n" +
	"\x10TransformRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\x04R\binstance\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"Q\n" +
	"\x11TransformResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04drop\x18\x02 \x01(\bR\x04drop\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"*\n" +
	"\fCloseRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\x04R\binstance2\xf4\x02\n" +
	"\x06Driver\x127\n" +
	"\x06Schema\x12\x11.psyduck.v1.Empty\x1a\x1a.psyduck.v1.SchemaResponse\x129\n" +
	"\x04Bind\x12\x17.psyduck.v1.BindRequest\x1a\x18.psyduck.v1.BindResponse\x12:\n" +
	"\aProduce\x12\x1a.psyduck.v1.ProduceRequest\x1a\x11.psyduck.v1.Event0\x01\x12:\n" +
	"\aConsume\x12\x18.psyduck.v1.ConsumeChunk\x1a\x11.psyduck.v1.Event(\x010\x01\x12H\n" +
	"\tTransform\x12\x1c.psyduck.v1.TransformRequest\x1a\x1d.psyduck.v1.TransformResponse\x124\n" +
	"\x05Close\x12\x18.psyduck.v1.CloseRequest\x1a\x11.psyduck.v1.EmptyB\"Z github.com/psyduck-etl/sdk/protob\x06proto3"

var (
	file_psyduck_proto_rawDescOnce sync.Once
	file_psyduck_proto_rawDescData []byte
)

func file_psyduck_proto_rawDescGZIP() []byte {
	file_psyduck_proto_rawDescOnce.Do(func() {
		file_psyduck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_psyduck_proto_rawDesc), len(file_psyduck_proto_rawDesc)))
	})
	return file_psyduck_proto_rawDescData
}

var file_psyduck_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_psyduck_proto_goTypes = []any{
	(*Empty)(nil),              // 0: psyduck.v1.Empty
	(*Spec)(nil),               // 1: psyduck.v1.Spec
	(*ResourceDescriptor)(nil), // 2: psyduck.v1.ResourceDescriptor
	(*SchemaResponse)(nil),     // 3: psyduck.v1.SchemaResponse
	(*SourceRange)(nil),        // 4: psyduck.v1.SourceRange
	(*BindRequest)(nil),        // 5: psyduck.v1.BindRequest
	(*BindResponse)(nil),       // 6: psyduck.v1.BindResponse
	(*ProduceRequest)(nil),     // 7: psyduck.v1.ProduceRequest
	(*Event)(nil),              // 8: psyduck.v1.Event
	(*ConsumeChunk)(nil),       // 9: psyduck.v1.ConsumeChunk
	(*TransformRequest)(nil),   // 10: psyduck.v1.TransformRequest
	(*TransformResponse)(nil),  // 11: psyduck.v1.TransformResponse
	(*CloseRequest)(nil),       // 12: psyduck.v1.CloseRequest
}
var file_psyduck_proto_depIdxs = []int32{
	1,  // 0: psyduck.v1.Spec.elem_type:type_name -> psyduck.v1.Spec
	1,  // 1: psyduck.v1.Spec.fields:type_name -> psyduck.v1.Spec
	1,  // 2: psyduck.v1.ResourceDescriptor.spec:type_name -> psyduck.v1.Spec
	2,  // 3: psyduck.v1.SchemaResponse.resources:type_name -> psyduck.v1.ResourceDescriptor
	4,  // 4: psyduck.v1.BindRequest.origin:type_name -> psyduck.v1.SourceRange
	0,  // 5: psyduck.v1.Driver.Schema:input_type -> psyduck.v1.Empty
	5,  // 6: psyduck.v1.Driver.Bind:input_type -> psyduck.v1.BindRequest
	7,  // 7: psyduck.v1.Driver.Produce:input_type -> psyduck.v1.ProduceRequest
	9,  // 8: psyduck.v1.Driver.Consume:input_type -> psyduck.v1.ConsumeChunk
	10, // 9: psyduck.v1.Driver.Transform:input_type -> psyduck.v1.TransformRequest
	12, // 10: psyduck.v1.Driver.Close:input_type -> psyduck.v1.CloseRequest
	3,  // 11: psyduck.v1.Driver.Schema:output_type -> psyduck.v1.SchemaResponse
	6,  // 12: psyduck.v1.Driver.Bind:output_type -> psyduck.v1.BindResponse
	8,  // 13: psyduck.v1.Driver.Produce:output_type -> psyduck.v1.Event
	8,  // 14: psyduck.v1.Driver.Consume:output_type -> psyduck.v1.Event
	11, // 15: psyduck.v1.Driver.Transform:output_type -> psyduck.v1.TransformResponse
	0,  // 16: psyduck.v1.Driver.Close:output_type -> psyduck.v1.Empty
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_psyduck_proto_init() }
func file_psyduck_proto_init() {
	if File_psyduck_proto != nil {
		return
	}
	file_psyduck_proto_msgTypes[8].OneofWrappers = []any{
		(*Event_Data)(nil),
		(*Event_Error)(nil),
		(*Event_Done)(nil),
	}
	file_psyduck_proto_msgTypes[9].OneofWrappers = []any{
		(*ConsumeChunk_Instance)(nil),
		(*ConsumeChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_psyduck_proto_rawDesc), len(file_psyduck_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_psyduck_proto_goTypes,
		DependencyIndexes: file_psyduck_proto_depIdxs,
		MessageInfos:      file_psyduck_proto_msgTypes,
	}.Build()
	File_psyduck_proto = out.File
	file_psyduck_proto_goTypes = nil
	file_psyduck_proto_depIdxs = nil
}
