// psyduck.proto is the wire contract between a psyduck host and a plugin
// subprocess, spoken over hashicorp/go-plugin's gRPC transport. It mirrors
// the sdk surface one-to-one:
//
//   sdk.Plugin.Name/Resources  <->  Driver.Schema
//   sdk.Plugin.Bind            <->  Driver.Bind   (returns an instance handle)
//   sdk.Instance.Produce       <->  Driver.Produce   (server stream)
//   sdk.Instance.Consume       <->  Driver.Consume   (bidirectional stream)
//   sdk.Instance.Transform     <->  Driver.Transform (unary)
//   sdk.Instance.Close         <->  Driver.Close
//
// Data items are opaque bytes, exactly as they are on the sdk's channel
// surface. Config crosses as the JSON object ConfigBlock.Encode produces.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: psyduck.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Driver_Schema_FullMethodName    = "/psyduck.v1.Driver/Schema"
	Driver_Bind_FullMethodName      = "/psyduck.v1.Driver/Bind"
	Driver_Produce_FullMethodName   = "/psyduck.v1.Driver/Produce"
	Driver_Consume_FullMethodName   = "/psyduck.v1.Driver/Consume"
	Driver_Transform_FullMethodName = "/psyduck.v1.Driver/Transform"
	Driver_Close_FullMethodName     = "/psyduck.v1.Driver/Close"
)

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Driver is the service a plugin subprocess serves. The host is the gRPC
// client for every RPC; data still flows plugin->host for Produce and
// host->plugin for Consume via streaming.
type DriverClient interface {
	Schema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SchemaResponse, error)
	Bind(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error)
	// Produce streams the instance's output. Data and error events are
	// interleaved; the stream ends cleanly when the producer closes its send
	// channel. Host cancellation propagates as stream context cancellation.
	Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Consume feeds the instance data. The host half-closes its send side
	// when the feed is exhausted (the sdk's recv close); the plugin ends the
	// stream when the consumer signals done. Error events flow back while
	// the stream is live.
	Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeChunk, Event], error)
	Transform(ctx context.Context, in *TransformRequest, opts ...grpc.CallOption) (*TransformResponse, error)
	// Close releases the instance handle and calls its Close.
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*Empty, error)
}

type driverClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverClient(cc grpc.ClientConnInterface) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) Schema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, Driver_Schema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Bind(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindResponse)
	err := c.cc.Invoke(ctx, Driver_Bind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Driver_ServiceDesc.Streams[0], Driver_Produce_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProduceRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Driver_ProduceClient = grpc.ServerStreamingClient[Event]

func (c *driverClient) Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeChunk, Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Driver_ServiceDesc.Streams[1], Driver_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeChunk, Event]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Driver_ConsumeClient = grpc.BidiStreamingClient[ConsumeChunk, Event]

func (c *driverClient) Transform(ctx context.Context, in *TransformRequest, opts ...grpc.CallOption) (*TransformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransformResponse)
	err := c.cc.Invoke(ctx, Driver_Transform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Driver_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServer is the server API for Driver service.
// All implementations must embed UnimplementedDriverServer
// for forward compatibility.
//
// Driver is the service a plugin subprocess serves. The host is the gRPC
// client for every RPC; data still flows plugin->host for Produce and
// host->plugin for Consume via streaming.
type DriverServer interface {
	Schema(context.Context, *Empty) (*SchemaResponse, error)
	Bind(context.Context, *BindRequest) (*BindResponse, error)
	// Produce streams the instance's output. Data and error events are
	// interleaved; the stream ends cleanly when the producer closes its send
	// channel. Host cancellation propagates as stream context cancellation.
	Produce(*ProduceRequest, grpc.ServerStreamingServer[Event]) error
	// Consume feeds the instance data. The host half-closes its send side
	// when the feed is exhausted (the sdk's recv close); the plugin ends the
	// stream when the consumer signals done. Error events flow back while
	// the stream is live.
	Consume(grpc.BidiStreamingServer[ConsumeChunk, Event]) error
	Transform(context.Context, *TransformRequest) (*TransformResponse, error)
	// Close releases the instance handle and calls its Close.
	Close(context.Context, *CloseRequest) (*Empty, error)
	mustEmbedUnimplementedDriverServer()
}

// UnimplementedDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServer struct{}

func (UnimplementedDriverServer) Schema(context.Context, *Empty) (*SchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Schema not implemented")
}
func (UnimplementedDriverServer) Bind(context.Context, *BindRequest) (*BindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bind not implemented")
}
func (UnimplementedDriverServer) Produce(*ProduceRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedDriverServer) Consume(grpc.BidiStreamingServer[ConsumeChunk, Event]) error {
	return status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedDriverServer) Transform(context.Context, *TransformRequest) (*TransformResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transform not implemented")
}
func (UnimplementedDriverServer) Close(context.Context, *CloseRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedDriverServer) mustEmbedUnimplementedDriverServer() {}
func (UnimplementedDriverServer) testEmbeddedByValue()                {}

// UnsafeDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServer will
// result in compilation errors.
type UnsafeDriverServer interface {
	mustEmbedUnimplementedDriverServer()
}

func RegisterDriverServer(s grpc.ServiceRegistrar, srv DriverServer) {
	// If the following call pancis, it indicates UnimplementedDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Driver_ServiceDesc, srv)
}

func _Driver_Schema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Schema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_Schema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Schema(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Bind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Bind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_Bind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Bind(ctx, req.(*BindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Produce_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProduceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverServer).Produce(m, &grpc.GenericServerStream[ProduceRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Driver_ProduceServer = grpc.ServerStreamingServer[Event]

func _Driver_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DriverServer).Consume(&grpc.GenericServerStream[ConsumeChunk, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Driver_ConsumeServer = grpc.BidiStreamingServer[ConsumeChunk, Event]

func _Driver_Transform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Transform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_Transform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Transform(ctx, req.(*TransformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Driver_ServiceDesc is the grpc.ServiceDesc for Driver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Driver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "psyduck.v1.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Schema",
			Handler:    _Driver_Schema_Handler,
		},
		{
			MethodName: "Bind",
			Handler:    _Driver_Bind_Handler,
		},
		{
			MethodName: "Transform",
			Handler:    _Driver_Transform_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Driver_Close_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Produce",
			Handler:       _Driver_Produce_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Consume",
			Handler:       _Driver_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "psyduck.proto",
}
