// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc/plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rpc_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{0}
}

type Spec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                     // JSON-encoded cty.Type
	DefaultValue  []byte                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"` // JSON-encoded cty.Value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_rpc_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Spec) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Spec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Spec) GetDefaultValue() []byte {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kinds         []string               `protobuf:"bytes,2,rep,name=kinds,proto3" json:"kinds,omitempty"` // PRODUCER, CONSUMER, TRANSFORMER (can have multiple)
	Specs         []*Spec                `protobuf:"bytes,3,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_rpc_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *Resource) GetSpecs() []*Spec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Resources     []*Resource            `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Variables     map[string][]byte      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // JSON-encoded cty.Values
	Functions     map[string]string      `protobuf:"bytes,4,rep,name=functions,proto3" json:"functions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // function names -> descriptions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_rpc_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *PluginInfo) GetVariables() map[string][]byte {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *PluginInfo) GetFunctions() map[string]string {
	if x != nil {
		return x.Functions
	}
	return nil
}

type GetPluginInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        *PluginInfo            `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginInfoResponse) Reset() {
	*x = GetPluginInfoResponse{}
	mi := &file_rpc_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoResponse) ProtoMessage() {}

func (x *GetPluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *GetPluginInfoResponse) GetPlugin() *PluginInfo {
	if x != nil {
		return x.Plugin
	}
	return nil
}

type CreateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  string                 `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	OptionsJson   []byte                 `protobuf:"bytes,2,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"` // JSON-encoded configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_rpc_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *CreateResourceRequest) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

type CreateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceResponse) Reset() {
	*x = CreateResourceResponse{}
	mi := &file_rpc_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponse) ProtoMessage() {}

func (x *CreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceResponse) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CreateResourceResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateResourceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_rpc_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ProducerStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerStartRequest) Reset() {
	*x = ProducerStartRequest{}
	mi := &file_rpc_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerStartRequest) ProtoMessage() {}

func (x *ProducerStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerStartRequest.ProtoReflect.Descriptor instead.
func (*ProducerStartRequest) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ProducerStartRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ConsumerStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerStartRequest) Reset() {
	*x = ConsumerStartRequest{}
	mi := &file_rpc_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerStartRequest) ProtoMessage() {}

func (x *ConsumerStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerStartRequest.ProtoReflect.Descriptor instead.
func (*ConsumerStartRequest) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ConsumerStartRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type TransformerProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformerProcessRequest) Reset() {
	*x = TransformerProcessRequest{}
	mi := &file_rpc_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformerProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformerProcessRequest) ProtoMessage() {}

func (x *TransformerProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformerProcessRequest.ProtoReflect.Descriptor instead.
func (*TransformerProcessRequest) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *TransformerProcessRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *TransformerProcessRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type TransformerProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformerProcessResponse) Reset() {
	*x = TransformerProcessResponse{}
	mi := &file_rpc_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformerProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformerProcessResponse) ProtoMessage() {}

func (x *TransformerProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformerProcessResponse.ProtoReflect.Descriptor instead.
func (*TransformerProcessResponse) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *TransformerProcessResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TransformerProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransformerProcessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_rpc_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *StopRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_rpc_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_rpc_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_rpc_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_rpc_plugin_proto protoreflect.FileDescriptor

const file_rpc_plugin_proto_rawDesc = "" +
	"\n" +
	"\x10rpc/plugin.proto\x12\vpsyduck.rpc\"\a\n" +
	"\x05Empty\"\x91\x01\n" +
	"\x04Spec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\fR\fdefaultValue\"]\n" +
	"\bResource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05kinds\x18\x02 \x03(\tR\x05kinds\x12'\n" +
	"\x05specs\x18\x03 \x03(\v2\x11.psyduck.rpc.SpecR\x05specs\"\xdd\x02\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\tresources\x18\x02 \x03(\v2\x15.psyduck.rpc.ResourceR\tresources\x12D\n" +
	"\tvariables\x18\x03 \x03(\v2&.psyduck.rpc.PluginInfo.VariablesEntryR\tvariables\x12D\n" +
	"\tfunctions\x18\x04 \x03(\v2&.psyduck.rpc.PluginInfo.FunctionsEntryR\tfunctions\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a<\n" +
	"\x0eFunctionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x15GetPluginInfoResponse\x12/\n" +
	"\x06plugin\x18\x01 \x01(\v2\x17.psyduck.rpc.PluginInfoR\x06plugin\"_\n" +
	"\x15CreateResourceRequest\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12!\n" +
	"\foptions_json\x18\x02 \x01(\fR\voptionsJson\"i\n" +
	"\x16CreateResourceResponse\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xb8\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12>\n" +
	"\bmetadata\x18\x02 \x03(\v2\".psyduck.rpc.Message.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x14ProducerStartRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"7\n" +
	"\x14ConsumerStartRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"l\n" +
	"\x19TransformerProcessRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12.\n" +
	"\amessage\x18\x02 \x01(\v2\x14.psyduck.rpc.MessageR\amessage\"|\n" +
	"\x1aTransformerProcessResponse\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.psyduck.rpc.MessageR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\".\n" +
	"\vStopRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\">\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa9\x02\n" +
	"\rPluginService\x12G\n" +
	"\rGetPluginInfo\x12\x12.psyduck.rpc.Empty\x1a\".psyduck.rpc.GetPluginInfoResponse\x12Y\n" +
	"\x0eCreateResource\x12\".psyduck.rpc.CreateResourceRequest\x1a#.psyduck.rpc.CreateResourceResponse\x12C\n" +
	"\fStopResource\x12\x18.psyduck.rpc.StopRequest\x1a\x19.psyduck.rpc.StopResponse\x12/\n" +
	"\x04Ping\x12\x12.psyduck.rpc.Empty\x1a\x13.psyduck.rpc.Status2\x92\x01\n" +
	"\x0fProducerService\x12B\n" +
	"\x05Start\x12!.psyduck.rpc.ProducerStartRequest\x1a\x14.psyduck.rpc.Message0\x01\x12;\n" +
	"\x04Stop\x12\x18.psyduck.rpc.StopRequest\x1a\x19.psyduck.rpc.StopResponse2\xc2\x01\n" +
	"\x0fConsumerService\x12?\n" +
	"\x05Start\x12!.psyduck.rpc.ConsumerStartRequest\x1a\x13.psyduck.rpc.Status\x121\n" +
	"\x04Send\x12\x14.psyduck.rpc.Message\x1a\x13.psyduck.rpc.Status\x12;\n" +
	"\x04Stop\x12\x18.psyduck.rpc.StopRequest\x1a\x19.psyduck.rpc.StopResponse2\xad\x01\n" +
	"\x12TransformerService\x12Z\n" +
	"\aProcess\x12&.psyduck.rpc.TransformerProcessRequest\x1a'.psyduck.rpc.TransformerProcessResponse\x12;\n" +
	"\x04Stop\x12\x18.psyduck.rpc.StopRequest\x1a\x19.psyduck.rpc.StopResponseB#Z!github.com/psyduck-etl/sdk/rpc/pbb\x06proto3"

var (
	file_rpc_plugin_proto_rawDescOnce sync.Once
	file_rpc_plugin_proto_rawDescData []byte
)

func file_rpc_plugin_proto_rawDescGZIP() []byte {
	file_rpc_plugin_proto_rawDescOnce.Do(func() {
		file_rpc_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_plugin_proto_rawDesc), len(file_rpc_plugin_proto_rawDesc)))
	})
	return file_rpc_plugin_proto_rawDescData
}

var file_rpc_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_rpc_plugin_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: psyduck.rpc.Empty
	(*Spec)(nil),                       // 1: psyduck.rpc.Spec
	(*Resource)(nil),                   // 2: psyduck.rpc.Resource
	(*PluginInfo)(nil),                 // 3: psyduck.rpc.PluginInfo
	(*GetPluginInfoResponse)(nil),      // 4: psyduck.rpc.GetPluginInfoResponse
	(*CreateResourceRequest)(nil),      // 5: psyduck.rpc.CreateResourceRequest
	(*CreateResourceResponse)(nil),     // 6: psyduck.rpc.CreateResourceResponse
	(*Message)(nil),                    // 7: psyduck.rpc.Message
	(*ProducerStartRequest)(nil),       // 8: psyduck.rpc.ProducerStartRequest
	(*ConsumerStartRequest)(nil),       // 9: psyduck.rpc.ConsumerStartRequest
	(*TransformerProcessRequest)(nil),  // 10: psyduck.rpc.TransformerProcessRequest
	(*TransformerProcessResponse)(nil), // 11: psyduck.rpc.TransformerProcessResponse
	(*StopRequest)(nil),                // 12: psyduck.rpc.StopRequest
	(*StopResponse)(nil),               // 13: psyduck.rpc.StopResponse
	(*Status)(nil),                     // 14: psyduck.rpc.Status
	nil,                                // 15: psyduck.rpc.PluginInfo.VariablesEntry
	nil,                                // 16: psyduck.rpc.PluginInfo.FunctionsEntry
	nil,                                // 17: psyduck.rpc.Message.MetadataEntry
}
var file_rpc_plugin_proto_depIdxs = []int32{
	1,  // 0: psyduck.rpc.Resource.specs:type_name -> psyduck.rpc.Spec
	2,  // 1: psyduck.rpc.PluginInfo.resources:type_name -> psyduck.rpc.Resource
	15, // 2: psyduck.rpc.PluginInfo.variables:type_name -> psyduck.rpc.PluginInfo.VariablesEntry
	16, // 3: psyduck.rpc.PluginInfo.functions:type_name -> psyduck.rpc.PluginInfo.FunctionsEntry
	3,  // 4: psyduck.rpc.GetPluginInfoResponse.plugin:type_name -> psyduck.rpc.PluginInfo
	17, // 5: psyduck.rpc.Message.metadata:type_name -> psyduck.rpc.Message.MetadataEntry
	7,  // 6: psyduck.rpc.TransformerProcessRequest.message:type_name -> psyduck.rpc.Message
	7,  // 7: psyduck.rpc.TransformerProcessResponse.message:type_name -> psyduck.rpc.Message
	0,  // 8: psyduck.rpc.PluginService.GetPluginInfo:input_type -> psyduck.rpc.Empty
	5,  // 9: psyduck.rpc.PluginService.CreateResource:input_type -> psyduck.rpc.CreateResourceRequest
	12, // 10: psyduck.rpc.PluginService.StopResource:input_type -> psyduck.rpc.StopRequest
	0,  // 11: psyduck.rpc.PluginService.Ping:input_type -> psyduck.rpc.Empty
	8,  // 12: psyduck.rpc.ProducerService.Start:input_type -> psyduck.rpc.ProducerStartRequest
	12, // 13: psyduck.rpc.ProducerService.Stop:input_type -> psyduck.rpc.StopRequest
	9,  // 14: psyduck.rpc.ConsumerService.Start:input_type -> psyduck.rpc.ConsumerStartRequest
	7,  // 15: psyduck.rpc.ConsumerService.Send:input_type -> psyduck.rpc.Message
	12, // 16: psyduck.rpc.ConsumerService.Stop:input_type -> psyduck.rpc.StopRequest
	10, // 17: psyduck.rpc.TransformerService.Process:input_type -> psyduck.rpc.TransformerProcessRequest
	12, // 18: psyduck.rpc.TransformerService.Stop:input_type -> psyduck.rpc.StopRequest
	4,  // 19: psyduck.rpc.PluginService.GetPluginInfo:output_type -> psyduck.rpc.GetPluginInfoResponse
	6,  // 20: psyduck.rpc.PluginService.CreateResource:output_type -> psyduck.rpc.CreateResourceResponse
	13, // 21: psyduck.rpc.PluginService.StopResource:output_type -> psyduck.rpc.StopResponse
	14, // 22: psyduck.rpc.PluginService.Ping:output_type -> psyduck.rpc.Status
	7,  // 23: psyduck.rpc.ProducerService.Start:output_type -> psyduck.rpc.Message
	13, // 24: psyduck.rpc.ProducerService.Stop:output_type -> psyduck.rpc.StopResponse
	14, // 25: psyduck.rpc.ConsumerService.Start:output_type -> psyduck.rpc.Status
	14, // 26: psyduck.rpc.ConsumerService.Send:output_type -> psyduck.rpc.Status
	13, // 27: psyduck.rpc.ConsumerService.Stop:output_type -> psyduck.rpc.StopResponse
	11, // 28: psyduck.rpc.TransformerService.Process:output_type -> psyduck.rpc.TransformerProcessResponse
	13, // 29: psyduck.rpc.TransformerService.Stop:output_type -> psyduck.rpc.StopResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_rpc_plugin_proto_init() }
func file_rpc_plugin_proto_init() {
	if File_rpc_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_plugin_proto_rawDesc), len(file_rpc_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_rpc_plugin_proto_goTypes,
		DependencyIndexes: file_rpc_plugin_proto_depIdxs,
		MessageInfos:      file_rpc_plugin_proto_msgTypes,
	}.Build()
	File_rpc_plugin_proto = out.File
	file_rpc_plugin_proto_goTypes = nil
	file_rpc_plugin_proto_depIdxs = nil
}
